.github/workflows/cleanup_branches.yml

This action remove all branches inactive in the last 15 days, I put some branches in the whitelist because I don't know what they contain.
I use this GA -> https://github.com/phpdocker-io/github-actions-delete-abandoned-branches
And I don't know if we need a specific token, on my fork it worked See https://github.com/Nicogene/appsAway that it has just 11 branches

Add cleanup action

---

.github/workflows/onAppsAwayChanges.yml
demos/cameraTiltCalib/composeGui.yml
demos/cameraTiltCalib/composeHead.yml
demos/demoTemplate/composeHead.yml.template
demos/faceAndPoseDetection/composeGui.yml
demos/faceAndPoseDetection/composeHead.yml
demos/googleDialog/composeGui.yml
demos/googleDialog/main.yml
demos/googleSpeechApp/composeGui.yml
demos/googleSpeechApp/main.yml
demos/googleSpeechProcessing/composeGui.yml
demos/googleVisionAI/composeGui.yml
demos/graspTheBall/composeGui.yml
demos/graspTheBall/composeHead.yml
demos/graspTheBallGazebo/composeGui.yml
demos/iCubGazeboGrasping/composeGui.yml
demos/iCubGazeboGrasping/main.yml
demos/robotBaseStartup/composeHead.yml
demos/robotGazebo/test-script.sh
demos/speechToText/composeGui.yml
demos/startQA/composeGui.yml
demos/superviseCalib/composeGui.yml
demos/superviseCalib/composeHead.yml
demos/yarpBasicDeploy/composeGui.yml
demos/yarpBasicDeploy/composeHead.yml
demos/yarpBasicDeploy/main.yml
demos/yarpBasicDeploy/test-script.sh
demos/yarpOpenFace/composeGui.yml
demos/yarpOpenFace/composeHead.yml
scripts/testApp.sh

With @lauracavaliere and @AlexAntn, we introduced the following changes:
- a github action called `onAppsawayChanges`, which sends a repository dispatch to code when there are changes to the deployments files;
- a `testApp.sh` script in `appsAway/scripts`, which checks if there are any failed containers and eventually prints the log;
- for `yarpBasicDeploy` and `robotGazebo` a `test-script.sh`, which emulates the cluster setup pipeline from the website. 
The `test-script.sh` is currently specific for each demo, as it includes the specific image to be tested. This script then runs the `testApp.sh` script which is generic. 
This PR should be merged after the [PR](https://github.com/icub-tech-iit/code/pull/629) on code, such that it will trigger the pipeline.

Triggering the testing pipeline 

---

.github/workflows/onAppsAwayChanges.yml
demos/robotGazebo/main.yml
demos/robotGazebo/test-script.sh
demos/yarpBasicDeploy/test-script.sh

This PR introduces the following changes:
- `test-script.sh` was updated to handle the **image name / version / tag** coming from `appsAway` or `code:`
-  if coming from `appsAway,`  the **image name / version / tag** are the default values defined in the script;
- if coming from `code,` the **image name / version / tag** are extracted from the `client-payload.`

Handle the testing pipeline triggered from code

---

demos/yarpBasicDeploy/composeGui.yml
demos/yarpBasicDeploy/gui/gui_conf.ini
demos/yarpBasicDeploy/main.yml
gui/main.py
scripts/appsAway_copyFiles.sh
scripts/appsAway_startApp.sh
scripts/appsAway_stopApp.sh

This PR handles local images inside the pipeline. 
As a _proof of concept_ we used `yarpBasicDeploy`, adding the following options to the gui:
- `LOCAL_IMAGE_FLAG`: specifies if a local image will be used 
- `LOCAL_IMAGE_NAME`: specifies the name of the local image
We introduced the following changes to the pipeline:
- **`appsAway_startApp.sh`**:
when `LOCAL_IMAGE_FLAG` is true, if there is no registry with the port 5000 running, we create it, rename the image appending `localhost:5000/` beforehand, and then push it to the _local registry_. Otherwise, we skip the creation of the registry:
- **`main.py`** of the gui and **`appsAway_copyFiles.sh`:** 
the `appsAway_copyFile.sh` is now in charge of handling the overwriting of the images onto the ymls, and not the gui anymore. 
The pipeline …

Handling local images inside the pipeline

---

scripts/ansible_setup/Makefile
scripts/ansible_setup/prepare_local_registry.yml
scripts/ansible_setup/setup_hosts_ini.sh
scripts/appsAway_copyFiles.sh
scripts/appsAway_startApp.sh

This PR introduces changes to make the local registry visible to the nodes inside the swarm.
As per [this](https://github.com/icub-tech-iit/code/issues/656#issuecomment-868350710) comment, by default the registry is insecure and Docker rejects it. To allow access, we need to modify the `/etc/docker/daemon.json` file inside each worker node with the following line:
```
>/etc/docker/daemon.json
{
"insecure-registries" : ["<REGISTRY_IP>:5000"]
}
```
and consequently, restart docker.
To handle this, we created a new Ansible playbook, called `prepare_local_registry.yml`, which we run from the cluster setup.
This is still draft as we need to integrate also changes inside the cluster setup.

Updating local images handling within swarm

---

scripts/appsAway_startApp.sh

This PR sees the implementation of a check for the GUI machine `DISPLAY` environment variable.
We use the following command to check the value of this variable in the machine through ssh:
```
ps -u $(id -u) -o pid= | xargs -I PID -r cat /proc/PID/environ 2> /dev/null | tr '\0' '\n' | grep ^DISPLAY=: | sort -u
```
We then export this value when running other start commands to this machine, correctly configuring the `DISPLAY` variable in order to launch GUI applications.
This PR is pending further testing on the testing setup (Erzelli).

Implementation of check for DISPLAY

---

demos/yarpBasicDeploy/gui/gui_conf.ini
demos/yarpBasicDeploy/test-script.sh
scripts/appsAway_copyFiles.sh
scripts/appsAway_setupCluster.sh
scripts/appsAway_startApp.sh
scripts/appsAway_stopApp.sh

With this PR we want to add the possibility to handle multiple local images directly through the cluster setup dialog on the website.
Below you can find the changes that we implemented in the scripts:
- **`appsAway_setupCluster.sh`** : we created the function `find_docker_images()` which:
- checks for the local registry: if it doesn't find it, it creates it; otherwise, it relaunches the registry service 
- for each image in `APPSAWAY_IMAGES`, tries to pull it from DockerHub:
- if successful, we append `${APPSAWAY_CONSOLENODE_ADDR}:5000/` to the image name, we push it into the local registry and we update the `APPSAWAY_IMAGES` variable
- if it's not successful, we check if the image is present locally 
- if yes, again we rename the image and we push it into the local registry, updating the …

Handle local images through the website

---

.github/workflows/triggering_new_app_test.yml
.github/workflows/updating_PR_body.yml

In this PR two new GitHub Actions have been implemented to handle the pipeline which works to test newly added applications. In particular:
- `triggering_new_app_test.yml` is triggered when a PR on the `add_app_*` branch is opened and sends a repository dispatch to code with the list of the apps to be tested, taken from the PR body, and the pr context;
- `updating_PR_body.yml` is triggered by repository dispatch from code and updates the body of the PR with the outcome of the test received from code.

Implemented changes to handle the pipeline to test newly added application

---

scripts/appsAway_setupCluster.sh

This PR updates the `appsAway_setupCluster.sh` script in order to parallelize the pull and push processes.
We introduced the following changes:
- we run the pull and push in **background**;
- we **wait** for the processes to be finished;
- in the current logic, we rely on the output of `docker pull` command to understand if we want to push the image downloaded from DockerHub or our own local version.  However, running the pull in background does not allow us to get the output of the command itself, unless we wait for the process to finish, which defeats the purpose of parallelizing. Thus, to solve this issue, we rely on [**`docker manifest inspect`**](https://docs.docker.com/engine/reference/commandline/manifest/#manifest-inspect) command, which tells us if the image exists on DockerHub …

Implemented parallel push / pull

---

demos/superviseCalib/composeHead.yml
demos/superviseCalib/gui/gui_conf.ini
demos/superviseCalib/main.yml
gui/main.py

With this PR we restructured the GUI in order to give the possibility to the user of choosing:
- the type of camera: rgb or event-driven
- the resolution (320x240, 640x480, 1024x768)
- the camera configuration file used to start the driver: for each type of camera and resolution, the user can select one of the proposed `.ini` files from the drop-down list. There, you also find a custom-file: if this option is selected, a text field is enabled and here the user must insert his custom file in order to start the application.
Moreover, we adapted the `composeHead.yml` to this new structure of the GUI, and now it covers all the cases to start the device in a clearer way: if the custom field is empty, we run the device with the file selected from the drop-down list, otherwise, we take the …

Restructuring the superviseCalib GUI and its composeHead.yml

---

.github/workflows/onAppsAwayChanges.yml

With this PR we restructured the list of the changed files in order to save only the directory of the demo without including the name of the changed file. In this way, we removed the duplicates avoiding checking the existence of the `test-script.sh` multiple times for the same demo.

Restructuring the list of the changed files on 'onAppsAwayChanges.yml'

---

.ci/docker-yarpbasic.yml
.ci/docker-yarpgazebo.yml
demos/graspTheBall/main.yml
demos/superviseCalib/main.yml

With this PR I removed the read and write flag from some `.ymls`  because it was not needed. The flag is required only when we want to change the permission of files created by the deployment.

Removed wrong read and write flag 

---

scripts/appsAway_cleanupCluster.sh
scripts/appsAway_registryLaunch.yml
scripts/appsAway_setupCluster.sh
scripts/appsAway_setupRegistry.sh
scripts/appsAway_stopApp.sh

With this PR we want to fix the error generated by the deployment if we stop an application and start it again.
The error was related to the fact that the `appsAway_stopApp.sh` removed the registry and thus when calling the `appsAway_startApp.sh` the registry didn't exist anymore (it was created by `appsAway_setupCluster.sh`).
To fix this, we:
- create the registry with `docker-compose`; this implied changing the structure of `appsAway_registryLaunch.yml` which has to be the one required by `docker-compose`
- remove the registry in a new script `appsAway_cleanupCluster.sh` which is called when we close the GUI (i.e. at the end of the script generated by robot-bazaar)
This implementation requires changing the website to update the generation of the `demoName_setup.sh`.

Fix stopping and starting application

---

scripts/appsAway_startApp.sh

With this PR we fixed an error (``` bash: -f command not found ```) generated by the `appsAway_startApp.sh` when using the console as GUI node.
We noticed that we were using a wrong variable, `_DOCKER_COMPOSE_BIN_GUI` instead of `_DOCKER_COMPOSE_BIN_CONSOLE`, when doing `${_DOCKER_COMPOSE_BIN_GUI} -f ${file} pull`.
After this change, we didn't encounter the error anymore.

Fixed wrong env variable when using the console as GUI node.

---

scripts/appsAway_cleanupCluster.sh
scripts/appsAway_setupRegistry.sh
scripts/appsAway_startApp.sh
scripts/appsAway_stopApp.sh

With this PR we want to update `appsAway_cleanupCluster.sh` in order to properly clean the system when the deployment exists with an error. 
In particular, we added different functions, each of which performs a specific task:
- remove a registry created by the deployment;
- remove all the services and containers launched by the deployment;
- remove all the volumes created by the deployment;
- remove all the nodes from the swarm and kill the swarm manager.
We structured the script in order to handle different cleaning options by passing them as input to the script itself. On the basis of the above, the possible options are:
- "registry"
- "stack"
- "volumes"
- "swarm"
- without passing any options we clean up everything (i.e. registry, stack, volumes, swarm)
The …

Updated appsAway_cleanupCluster.sh to clean the machine when exiting the deployment

---

scripts/appsAway_setupCluster.sh
scripts/appsAway_setupRegistry.sh
scripts/appsAway_startApp.sh

This PR increases the speed of the deployment by removing the local registry when it is not needed. In the case where there is one node in the cluster, or when all images are found in Dockerhub, the local registry is avoided. Thus saving the time it takes to push into it and pull again.
Notable changes:
- In `appsAway_setupRegistry.sh` we inspect the manifest of the image to know which images are local and which remote. If at least one image is local, and there is more than one node in the cluster, the registry is created.
- Image names are only retagged with `{CONSOLE_IP}:5000/image-name` if there is at least one local image and the number of nodes is greater than one.
- Added a new exported variable `MUST_PULL` to identify whether or not the registry has been created or if there is at …

Speeded up pipeline by making local registry conditional

---

.ci/docker-compose.yml
.ci/docker-yarpbasic.yml
.ci/docker-yarpgazebo.yml
demos/cameraTiltCalib/main.yml
demos/demoTemplate/main.yml.template
demos/faceAndPoseDetection/main.yml
demos/funnyThingsApp/main.yml
demos/googleDialog/composeGui.yml
demos/googleDialog/main.yml
demos/googleSpeechApp/composeGui.yml
demos/googleSpeechApp/main.yml
demos/googleSpeechProcessing/composeGui.yml
demos/googleSpeechProcessing/main.yml
demos/googleVisionAI/main.yml
demos/graspTheBall/main.yml
demos/graspTheBallGazebo/main.yml
demos/iCubGazeboGrasping/main.yml
demos/robotBaseStartup/main.yml
demos/robotGazebo/main.yml
demos/speechToSpeech/main.yml
demos/speechToText/composeGui.yml
demos/speechToText/main.yml
demos/startQA/composeGui.yml
demos/startQA/main.yml
demos/superviseCalib/main.yml
demos/textToSpeech/main.yml
demos/yarpBasicDeploy/main.yml
demos/yarpOpenFace/main.yml
scripts/appsAway_setupCluster.sh
scripts/converter.py

With this PR different changes have been implemented in order to fix different issues when launching `yarpserver` through the deployment. In particular:
- we replaced `yarpserver --write` with `yarpserver --read` in all ymls in order to use the correct IP address when launching `yarpserver`, without creating connection issues between the host and the containers;
- we updated the ymls taking the correct namespace from the `yarp_namespace.conf` file and waiting for `/<namespace>` when launching a `yarp device` through the deployment; only in the particular case where the namespace is `/root`, since the `yarp_namespace.conf` file is not created, we instead wait for `/root`;
- we changed the way we set the YARP configuration in our `appsAway_setupCluster.sh`: summarizing we use the default …

Fixed issues when launching yarpserver through the deployment

---

demos/robotGazebo/composeGui.yml
scripts/appsAway_checkAppRunning.sh
scripts/appsAway_cleanupCluster.sh
scripts/appsAway_setupCluster.sh

This PR introduces the following changes to handle the deployment on a machine with no `yarp` installed:
- it detects the `cameraCalibration` and `demoRedBall` contexts only if `yarp` is installed on the console;
- it updates the `appsAway_cleanupCluster` to remove `iCubApps/${APPSAWAY_APP_NAME}` folder on all the machines in the cluster when we exit the deployment.
I also took the chance to update the `robotGazebo` `composeGui.yml` to wait for `yarp` to be up before running `gazebo`.

Fixes to run deployment with no yarp installed

---

gui/main.py
scripts/appsAway_checkAppRunning.sh
scripts/appsAway_guiLaunch.yml
scripts/appsAway_setupGui.sh

This PR introduces the recent changes made to the GUI. as part of issue #810 
We have changed the following:
- The deployment GUI is now launched from a container, instead of installing and launching from the host machine. 
- The deployment of the GUI image is done by the `appsAway_setupGui.sh` script. The script also initializes the two pipe files to communicate to and from the GUI.
This part of the PR adds the `appsAway_setuoGui.sh` script responsible for launching and communicating with the GUI. The deployment of the container is done by using a compose file `appsAway_guiLaunch.yml` which shares all the required devices and starts the GUI itself. Finally, it introduces changes to the `main.py` to account for the new way the GUI operates, using `pipe` files to launch the commands …

Changing GUI from launching on host to launch from container

---

scripts/appsAway_startApp.sh

This PR adds to `appsAway_startApp.sh` an additional check to verify the current state of each service. We now wait until the `Preparing` phase has finished before launching the services.

Wait for swarm to pull the images

---

demos/funnyThingsApp/composeGui.yml
scripts/appsAway_setupCluster.sh
scripts/appsAway_startApp.sh

Currently, if you launch the `funnyThingsApp` deployment without specifying a path for import/export the container hosting the funny things GUI fails to open.
This is unexpected behavior since the user may be interested in testing the functionality of funny things without necessarily wanting to import or export files.
This PR addresses this by creating an empty directory in `/tmp` and sharing this volume with the container if no other path is specified.

Make import/export in funnythings GUI optional

---

demos/googleDialog/composeGui.yml
demos/googleSpeechApp/composeGui.yml
demos/googleSpeechProcessing/composeGui.yml
demos/speechToSpeech/composeGui.yml
demos/speechToText/composeGui.yml
demos/startQA/composeGui.yml

This PR modifies the calls to the microphone yarpdev to remove flag parameters like `--channels` and `--rate`. These parameters will now be part of the images themselves in the form of config files.

Remove parameters from speech ymls

---

demos/graspTheBallGazebo/composeGui.yml
demos/graspTheBallGazebo/main.yml

Without setting these wait/dependencies the results are undefined behaviors. With these changes the demo take a little bit longer to start, but it starts always properly.

[graspTheBallGazebo] Add proper dependencies among services

---

demos/graspTheBallGazebo/composeGui.yml
demos/iCubGazeboGrasping/composeGui.yml

This PR removes the sharing of `cuda` volumes, which make `graspTheBallGazebo` and `iCubGazeboGrasping` fail on systems where `cuda` is detected (probably we overwrite some libraries when sharing these folders).
This works on systems with and without `cuda`.

Removed cuda volumes in graspTheBallGazebo and iCubGazeboGrasping

---

demos/funnyThingsApp/composeGui.yml
demos/funnyThingsApp/gui/gui_conf.ini
demos/googleDialog/composeGui.yml
demos/googleDialog/gui/gui_conf.ini
demos/googleDialog/main.yml
demos/googleSpeechApp/composeGui.yml
demos/googleSpeechApp/gui/gui_conf.ini
demos/googleSpeechApp/main.yml
demos/googleSpeechProcessing/composeGui.yml
demos/googleSpeechProcessing/gui/gui_conf.ini
demos/googleSpeechProcessing/main.yml
demos/googleVisionAI/composeGui.yml
demos/googleVisionAI/gui/gui_conf.ini
demos/googleVisionAI/main.yml
demos/speechToSpeech/composeGui.yml
demos/speechToSpeech/gui/gui_conf.ini
demos/speechToSpeech/main.yml
demos/speechToText/composeGui.yml
demos/speechToText/gui/gui_conf.ini
demos/speechToText/main.yml
demos/startQA/composeGui.yml
demos/startQA/gui/gui_conf.ini
demos/startQA/main.yml
demos/textToSpeech/composeGui.yml
demos/textToSpeech/gui/gui_conf.ini
demos/textToSpeech/main.yml
scripts/appsAway_copyFiles.sh

This PR allows for copying the Google authorization key from the console to any other machine in the cluster that may need it. Furthermore, the path for the key is now fixed since it is the new location of the file after copying.
All the ymls that use Google Services have been updated. This change has been tested in PARROT application and we could see it works well.

Share Google Key file to other machines in cluster

---

demos/graspTheBall/gui/gui_conf.ini
demos/graspTheBall/main.yml

In this PR, the GUI option to choose the version of the hand has been removed from `graspTheBall` since not used by our deployment. Consequently, the `ymls` have been updated with this change.

Removed HAND_VERSION from graspTheBall since not used

---

demos/googleSpeechApp/main.yml

This PR avoids connecting `googleSpeechProcess` and `googleSynthesis` when `GOOGLE_INPUT` is enabled.

Fix googleSpeechApp when all options are enabled

---

demos/startQA/composeGui.yml

This PR makes the startQA application only activate the microphone device when necessary (that is, when the user selects `Google speech-to-text`.
Previously it was always activated which was an unnecessary grab of external resources.
This means that the GUI does not do anything if one does not select `speech-to-text` nor `text-to-speech` (which makes sense since you don't need a GUI in that case, everything is text-based).
It has been tested to confirm this does not break the behavior of the app otherwise.

StartQA: activate microphone only when necessary

---

demos/faceAndPoseDetection/composeGui.yml
demos/faceAndPoseDetection/gui/gui_conf.ini
demos/faceAndPoseDetection/main.yml

Since we currently have problems in running `yarpOpenPose` on a cuda machine through `docker swarm`, this PR removes `yarpOpenPose` from the deployment and the gui options in view of the first release.
I'm going to update the instructions on the website too.

[faceAndPoseDetection] removed openpose

---

.github/workflows/release.yml

This creates a release of appsAway with the same tag of the latest superbuild released

Add release workflow triggered by code

---

scripts/appsAway_addResources.sh

This PR moves the check for an app running from the scripts in `appsAway` to the setup script generated from `robot-bazaar`.
This allows us to always check if an app is running, without having issues over the presence of `appsAway` folder.

moved app running check to the setup script

---

scripts/ansible_setup/setup_hosts_ini.sh
scripts/appsAway_checkDocker.sh

This PR introduces a new check in the `ansible` step, where we check if a machine has an NVIDIA GPU using `lshw -C display`.
If a  GPU is detected, we add the machine to the list of hosts that require a `cuda` configuration, which installs `nvidia-docker2` and sets the correct configuration of ``/etc/docker/daemon.json`.
With this, in machines that use the GPU as a display device, we can use them as `icubgui` machines without any other changes in deployment or images.

check for machines with nvidia gpus to install the correct configuration

---

modules/checkRobotInterface/src/main.cpp

I substituted `asDouble()` method in favour of `asFloat64()`  in order to make `checkRobotInterface` compatible with YARP version 3.7.
See [here](https://github.com/robotology/yarp/releases/tag/v3.7.0).
I compiled `checkRobotInterface` without any error.

now checkRobotInterface is compatible with yarp 3.7

---

demos/iCubTest/composeGui.yml

The `yarp wait` is replaced by the `checkRobotInterface` function implemented by @valegagge , which provides better control and avoids unnecessary blocking situations

Clean and remove waiting of the yarp ports

---

demos/blenderController/composeHead.yml
demos/demoTemplate/composeHead.yml.template
demos/graspTheBall/composeHead.yml
demos/iCubTest/composeHead.yml
demos/robotBaseStartup/composeHead.yml
demos/superviseCalib/composeHead.yml
demos/yarpOpenFace/composeHead.yml

This PR changes the way we call `yarprobotinterface` in our deployment. Wrapping it in a shell command like we do now prevents the program from closing properly. 
To allow for proper cleanup of the program we put `yarprobotinterface` as the only command in the service. To still allow the system to wait for yarp, and to remain resilent to eventual issues, we added a restart policy of `on-failure`, so that the service is open as soon as th external conditions allow it. 
This has been tested with `iCubTest` and the results were satisfactory.

Changed the way we call yarprobotinterface in the deployment
